<a href="https://colab.research.google.com/github/PrasantIITM/ma22c033_2023_PL/blob/main/Assignment%204/Numpy_blitz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math

In [2]:
A = [0.1, 1.3, 0.4, 0.5]    # list
a = np.array(A)             # numpy array

type(a), type(A)

(numpy.ndarray, list)

In [3]:
a.dtype

dtype('float64')

In [4]:
2*a

array([0.2, 2.6, 0.8, 1. ])

In [5]:
2*A

[0.1, 1.3, 0.4, 0.5, 0.1, 1.3, 0.4, 0.5]

In [6]:
n = 100000
x = np.linspace(0, 2*np.pi, n)

In [7]:
# list comprehension
%timeit y = [math.sin(x[i]) * math.exp(-x[i]) for i in range(n)]

# use numpy ufuncs
%timeit y = np.sin(x) * np.exp(-x)

77 ms ± 33.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.48 ms ± 41.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
def f(v):                       # apply f to one scalar value v
    return math.sin(v) * math.exp(-v)

In [9]:
vectorizedf = map(f, x)

In [10]:
F = np.vectorize(f)

In [11]:
# use map
%timeit y = list(map(f, x))

# use numpy's vectorize
%timeit y = F(x)

# use numpy's ufunc
%timeit y = np.sin(x) * np.exp(-x)

36 ms ± 834 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
35.1 ms ± 942 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.41 ms ± 1.03 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
%timeit for x in range(1000000): x**3
%timeit for x in np.arange(1000000): x**3

327 ms ± 4.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
151 ms ± 52.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
a = np.random.randint(0,9,5)
a

array([2, 4, 0, 3, 1])

In [14]:
a[::]

array([2, 4, 0, 3, 1])

In [15]:
a[-3:]

array([0, 3, 1])

In [16]:
a[-1], a[len(a)-1]

(1, 1)

In [17]:
a[-4:-1:2]

array([4, 3])

In [18]:
slice = range(-4,-1,2)
a[-4:-1:2], a[slice]

(array([4, 3]), array([4, 3]))

In [19]:
a = np.array([1,2,3])
b = np.array([3,4,5,6])

In [20]:
a = b
a[0] = 1
a

array([1, 4, 5, 6])

In [21]:
b

array([1, 4, 5, 6])

In [22]:
a = np.array([1,2,3])      # This is Object1 and "a" is a name for it.
b = np.array([3,4,5,6])    # This is Object2 and "b" is a name for it.

In [23]:
id(a), id(b)

(138839928394384, 138839928392752)

In [24]:
a = b  # a is no longer a name for Object1, it is now a name for Object2.

In [25]:
id(a), id(b)

(138839928392752, 138839928392752)

In [26]:
a = np.array([1,2,3])    # Object1
b = np.array([3,4,5,6])  # Object2
a = b.copy()             # Copies Object2, and binds a to the copy
a[0] = 2                 # Only the copied (new) object is changed

In [27]:
a, b

(array([2, 4, 5, 6]), array([3, 4, 5, 6]))

In [28]:
Amat = [[1,2],
        [3,4]]
Amat

[[1, 2], [3, 4]]

In [29]:
amat = np.array(Amat)
amat

array([[1, 2],
       [3, 4]])

In [30]:
type(A), type(a)

(list, numpy.ndarray)

In [31]:
2*Amat

[[1, 2], [3, 4], [1, 2], [3, 4]]

In [32]:
2*amat

array([[2, 4],
       [6, 8]])

In [33]:
amat

array([[1, 2],
       [3, 4]])

In [34]:
amat * amat

array([[ 1,  4],
       [ 9, 16]])

In [35]:
import sys
print(sys.version)

3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]


In [36]:
amat @ amat

array([[ 7, 10],
       [15, 22]])

In [37]:
np.dot(amat, amat)  # dot(A,B) = matrix A multiplied by matrix B

array([[ 7, 10],
       [15, 22]])

In [38]:
amat.dot(amat)

array([[ 7, 10],
       [15, 22]])

In [39]:
amat.dot(amat)

array([[ 7, 10],
       [15, 22]])

In [40]:
np.linalg.matrix_power(amat, 2)

array([[ 7, 10],
       [15, 22]])

In [41]:
A = np.array([[7, 8, 5, 1], [2, 5, 5, 2], [9, 6, 8, 9]])
A

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [42]:
A[1, :], A[:, 2]

(array([2, 5, 5, 2]), array([5, 5, 8]))

In [43]:
A[:3:2, :3]

array([[7, 8, 5],
       [9, 6, 8]])

In [44]:
M = np.array([[7, 8, 5, 1], [2, 5, 5, 2], [9, 6, 8, 9]])
M

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [45]:
M.reshape(2, 6)

array([[7, 8, 5, 1, 2, 5],
       [5, 2, 9, 6, 8, 9]])

In [46]:
M.ravel()

array([7, 8, 5, 1, 2, 5, 5, 2, 9, 6, 8, 9])

In [47]:
A = np.array(M, order='F')
A

array([[7, 8, 5, 1],
       [2, 5, 5, 2],
       [9, 6, 8, 9]])

In [48]:
A.ravel(order='A')

array([7, 2, 9, 8, 5, 6, 5, 5, 8, 1, 2, 9])

In [49]:
M.ravel(order='A')

array([7, 8, 5, 1, 2, 5, 5, 2, 9, 6, 8, 9])

In [50]:
N = np.arange(25).reshape(5,5)
N

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
mask = (N>7) & (N<18)
mask

array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False],
       [False, False, False, False, False]])

In [52]:
N[mask]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [53]:
i, j = np.where(mask)
i, j

(array([1, 1, 2, 2, 2, 2, 2, 3, 3, 3]), array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2]))

In [54]:
data = np.random.randint(low=0, high=10, size=30)

In [55]:
T2 = np.reshape(data, (6, 5))                      # 2D array
T2

array([[8, 6, 0, 3, 5],
       [1, 1, 8, 6, 4],
       [1, 5, 8, 9, 9],
       [5, 8, 4, 7, 3],
       [1, 6, 7, 9, 3],
       [8, 0, 8, 5, 5]])

In [56]:
T3 = np.reshape(data, (2, 3, 5))                  # 3D array
T3

array([[[8, 6, 0, 3, 5],
        [1, 1, 8, 6, 4],
        [1, 5, 8, 9, 9]],

       [[5, 8, 4, 7, 3],
        [1, 6, 7, 9, 3],
        [8, 0, 8, 5, 5]]])

In [57]:
print('T3 is a ', T3.ndim, 'dimensional array of shape ', T3.shape)
print('T2 is a ', T2.ndim, 'dimensional array of shape ', T2.shape)
print('data is a ', data.ndim, 'dimensional array of shape ', data.shape)

T3 is a  3 dimensional array of shape  (2, 3, 5)
T2 is a  2 dimensional array of shape  (6, 5)
data is a  1 dimensional array of shape  (30,)
