<a href="https://colab.research.google.com/github/PrasantIITM/ma22c033_2023_PL/blob/main/Assignment%205/Row_swap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [5]:
def swaprow(i, j, A):
    tmp = A[i, :]
    A[i, :] = A[j, :]
    A[j, :] = tmp
    return A

A = np.array([[1, 3, 2],
              [5, 5, 6],
              [4, 7, 9]])
result = swaprow(0, 2, A)
print(result)

[[4 7 9]
 [5 5 6]
 [4 7 9]]


In [6]:
def swaprow(i, j, A):
    tmp = A[i, :].copy()  # Make a copy of the row by which the value  of tmp not change if we change velue of A[i,:]
    A[i, :] = A[j, :]
    A[j, :] = tmp
    return A
A = np.array([[1, 3, 2],
              [5, 5, 6],
              [4, 7, 9]])
result = swaprow(0, 2, A)
print(result)

[[4 7 9]
 [5 5 6]
 [1 3 2]]
