<a href="https://colab.research.google.com/github/PrasantIITM/ma22c033_2023_PL/blob/main/Assignment%208/Column_space.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
from scipy.linalg import svd, qr
A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]])

**Task 1**

In [32]:
u,s,vT=svd(A)

In [33]:
print(u)

[[ 2.66235859e-01  1.70641342e-01  9.48683298e-01]
 [ 5.39615303e-01 -8.41911709e-01 -5.55111512e-17]
 [-7.98707576e-01 -5.11924025e-01  3.16227766e-01]]


In [34]:
print(u.T)

[[ 2.66235859e-01  5.39615303e-01 -7.98707576e-01]
 [ 1.70641342e-01 -8.41911709e-01 -5.11924025e-01]
 [ 9.48683298e-01 -5.55111512e-17  3.16227766e-01]]


In [35]:
for i in range(3):
  basis_svd=u.T[i]

  print(basis_svd,end="  ")

[ 0.26623586  0.5396153  -0.79870758]  [ 0.17064134 -0.84191171 -0.51192403]  [ 9.48683298e-01 -5.55111512e-17  3.16227766e-01]  

In [36]:
q,r=qr(A)

In [37]:
print(q)

[[-0.26726124  0.95618289 -0.11952286]
 [-0.53452248 -0.04390192  0.84401323]
 [ 0.80178373  0.28945968  0.52283453]]


In [38]:
print(r)

[[-3.74165739e+00  7.48331477e+00 -1.28285396e+01  9.08688223e+00]
 [ 0.00000000e+00 -1.98602732e-15 -1.31705767e-01 -1.75607689e-01]
 [ 0.00000000e+00  0.00000000e+00  2.53203970e+00  3.37605293e+00]]


In  QR factorization the set of column vectors of Q work as a orthogonal basis for the column space matrix A. Hence the columns vectors of Q is also a basis for the column space of Matrix A.

In [39]:
for i in range(3):
  basis_qr=q.T[i]
  # B=np.concatenate(q.T[i])

  print(basis_qr,end="  ")

[-0.26726124 -0.53452248  0.80178373]  [ 0.95618289 -0.04390192  0.28945968]  [-0.11952286  0.84401323  0.52283453]  

In [40]:
q @ q.T

array([[ 1.00000000e+00,  1.92665606e-16, -4.22849884e-17],
       [ 1.92665606e-16,  1.00000000e+00, -8.94625747e-18],
       [-4.22849884e-17, -8.94625747e-18,  1.00000000e+00]])

**Task 2**

Suppose B1 AND B2 are two basis for vector space V. Now the question arise can without knowing the vectorspce if only the basis are availabel can they generate the same vector space ?
 Two verify this we find the rank of matrix [B1, B2]= rank of matrix(B1)=rank of matrix(B2) . Then we can say that B1 spans B2  

In [41]:
aug_uq=np.vstack((u,q)) # here we make the [u.T,q.T].T matrix as we rank of A=rank of A.T
print(aug_uq)

[[ 2.66235859e-01  1.70641342e-01  9.48683298e-01]
 [ 5.39615303e-01 -8.41911709e-01 -5.55111512e-17]
 [-7.98707576e-01 -5.11924025e-01  3.16227766e-01]
 [-2.67261242e-01  9.56182887e-01 -1.19522861e-01]
 [-5.34522484e-01 -4.39019222e-02  8.44013232e-01]
 [ 8.01783726e-01  2.89459681e-01  5.22834534e-01]]


In [42]:
np.linalg.matrix_rank(aug_uq)

3

As rank(u) =rank(q) =rank(aug_uq). So from here we can say that the basis we got from svd matrix is able to generate the basis we got from qr. So Both the basis can generate same column space.

**Task 3**

In [43]:
B=np.random.rand(500,500)
U,S,VT=svd(B)
Q,R=qr(B)
%timeit U,S,VT
%timeit Q,R

116 ns ± 31.9 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
79.6 ns ± 13.9 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In above as we can see that QR factorization is faster than svd.