<a href="https://colab.research.google.com/github/PrasantIITM/ma22c033_2023_PL/blob/main/Assignment%206/Pairwise_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import numpy as np
x = np.random.rand(5)
print(x)
D=np.array([[x[j]-x[i] for i in range(5)]for j in range(5)])
print("D=", D)

[0.7298149  0.32714793 0.87754057 0.27337102 0.60305931]
D= [[ 0.          0.40266697 -0.14772567  0.45644388  0.12675559]
 [-0.40266697  0.         -0.55039264  0.05377691 -0.27591138]
 [ 0.14772567  0.55039264  0.          0.60416955  0.27448126]
 [-0.45644388 -0.05377691 -0.60416955  0.         -0.32968829]
 [-0.12675559  0.27591138 -0.27448126  0.32968829  0.        ]]
